# ======================
# General Settings
# ======================
project_name: fau_emotion_pipeline
seed: 42
device: cuda

# ======================
# Data Settings
# ======================
data:
  dataset_name: BP4D+           # or DISFA / Aff-Wild2 / RAF-DB
  dataset_root: ./data/videos/  # root path where video frames are stored
  label_file: ./data/labels.csv # path to AU or emotion label file
  frame_height: 224
  frame_width: 224
  clip_length: 16
  num_workers: 4
  batch_size: 8
  shuffle: true

# ======================
# Stage 1: FAU Detection
# ======================
stage1:
  num_faus: 12
  video_mae_name: MCG-NJU/videomae-base
  freeze_video_mae: true
  gnn_out_dim: 256
  learning_rate: 0.0001
  weight_decay: 0.01
  num_epochs: 20
  save_path: ./checkpoints/stage1_model.pt

# ======================
# Stage 2: Emotion Classification
# ======================
stage2:
  emotion_dataset: Aff-Wild2    # or RAF-DB
  num_emotions: 7               # Aff-Wild2: 7, RAF-DB: 12
  freeze_stage1: true
  learning_rate: 0.0002
  weight_decay: 0.01
  num_epochs: 15
  save_path: ./checkpoints/stage2_model.pt

# ======================
# Logging / Checkpoint
# ======================
log_interval: 10
log_dir: ./logs/
checkpoint_dir: ./checkpoints/
resume_checkpoint: null  # path to resume model if needed

# ======================
# Testing & Evaluation
# ======================
test:
  stage: 1                 # 1 or 2
  test_split_file: ./data/test_split.csv
  metrics: ["f1", "accuracy", "ccc"]  # for AU and emotion tasks
